services:
  db:
    image: 'postgres:14.8-alpine'
    container_name: 'democruddb'
    ports:
      - "5432:5432"
    restart: 'unless-stopped'
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: democruddb
    networks:
      - fullstack
    volumes:
      - cruddemoDB:/var/lib/postgresql/data
volumes:
  cruddemoDB:
networks:
  fullstack:
    driver: bridge
